cbv/basicapp/urls.py
from django.urls import path
from . import views

app_name="basicapp"

urlpatterns=[
    path('',views.Tempview.as_view(),name='home'),
    
    # path('schooldetails/',views.school_details_view.as_view()),
    
    path('base/',views.school_list_view.as_view(),name="list"),
    
    path('base/<int:pk>/',views.school_details_view.as_view(),name='detail'),

    path('base/create/',views.school_create_view.as_view(),name='create'),
    
    path('base/update/<int:pk>',views.school_update_view.as_view(),name='update'),

    path('base/delete/<int:pk>',views.school_delete_view.as_view(),name="delete"),


    #---------STUDENT URLS-----------------

    path('base/create_student/',views.student_create_view.as_view(),name="create_student"),

    path('base/update_student/<int:pk>',views.student_update_view.as_view(),name="update_student"),

    path('base/delete_student/<int:pk>',views.student_delete_view.as_view(),name="delete_student"),



    
    

]

cbv/cbv/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('basicapp.urls')),
]

cbv/basicapp/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class School(models.Model):
    
    name=models.CharField(max_length=200)
    principal=models.CharField(max_length=256)
    location=models.CharField(max_length=220)


    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse("basicapp:detail",kwargs={'pk':self.pk})

class Student(models.Model):

    name=models.CharField(max_length=200)
    age=models.PositiveIntegerField()
    school=models.ForeignKey(School,related_name="students",on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basicapp:detail",kwargs={'pk':self.school.pk})

cbv/basicapp/views.py
from django.shortcuts import render
from django.views.generic import (View,TemplateView,ListView,DetailView,
                                    CreateView,UpdateView,DeleteView)

from django.urls import reverse,reverse_lazy
from django.http import HttpResponse
from . import models

#FUNCTION BASED VIEW
# def index(request):
#     return render(request,"index.html")


#CLASS BASED VIEW
# class CBview(View):
#     def get(self,request):
#         return HttpResponse("CLASS BASED VIEWS KARKE KYA MAZA AYA")



#CLASS BASED TEMPLATE VIEW
# class Tempview(TemplateView):
#     template_name='index.html'

#     def get_context_data(self, **kwargs):

#         context=super().get_context_data(**kwargs)

#         context["cricketername"]="STEVE SMITH!"
#         return context




class Tempview(TemplateView):
    template_name="index.html"

class school_list_view(ListView):

    # LOWERS model name ie : school and creates school_list .This is returned by ListView default
    #you can change it by using below approach
    
    model=models.School
    context_object_name='schools'
    
    #Now you can reference using schools in templates
    #If you do not do this you can refer it using *school_list*



#---------STUDENT--------------------

class student_create_view(CreateView):
    model=models.Student
    fields=('name','age','school')


class student_update_view(UpdateView):
    model=models.Student
    fields=('name','age','school')

class student_delete_view(DeleteView):
    model=models.Student
    success_url=reverse_lazy("basicapp:list")


#------------SCHOOL-----------------------    

class school_details_view(DetailView):

    #This just return lowered modelname ie returns school
    context_object_name="school_detail"
    model=models.School
    template_name='basicapp/school_detail.html'


class school_create_view(CreateView):
    model=models.School
    fields=('name','principal','location')



class school_update_view(UpdateView):
    model=models.School
    fields=('name','principal')



class school_delete_view(DeleteView):
    model=models.School
    #This all are already defined class variables
    success_url=reverse_lazy("basicapp:list")
    

cbv/basicapp/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BASE</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
<body>
    
    <nav class="navbar navbar-inverse navbar-static-top">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class="navbar-link" href="{% url 'basicapp:home' %}">Home</a></li>
            <li><a class="navbar-link"  href="{% url 'basicapp:list' %}">SCHOOLS</a></li>

        </ul>
    </nav>
    
    <div class="container">
        
        {% block body_block %}


        {% endblock %}
        
    </div>
   
</body>
</html>

cbv/basicapp/templates/basicapp/school_confirm_delete.html
{% extends 'basicapp/base.html' %}


{% block body_block %}

    <h1>DELETE {{school.name}} ??</h1>
    <form method="POST">
        {% csrf_token %}

        <input type="submit" class="btn btn-danger" value="DELETE">

        <a href="{% url 'basicapp:detail' pk=school.pk %}">CANCEL</a>
    
    </form>

{% endblock%}

cbv/basicapp/templates/basicapp/school_detail.html
{% extends 'basicapp/base.html' %}

{% block body_block %}
    <div class="jumbotron">
        

        <div class="panel panel-info">

            <div class="panel-footer">
               Welcome to <strong>{{school_detail.name}}</strong>
            </div>    
            <div class="panel-footer">
                <b>Principal</b>: {{ school_detail.principal }}
            </div>    
            <div class="panel-footer">
                <b>Location</b>: {{school_detail.location }} 
             </div>

       </div>
        
        <div class="alert alert-info">STUDENTS </div>
        
        <ul class="list-group">
            {% for student in school_detail.students.all %}
            <li class="list-group-item">
             
                {{student.name}} who is {{student.age}} years old.
                <a class="btn btn-danger" href="{% url 'basicapp:delete_student' pk=student.pk%}"> DELETE STUDENT</a>
            
            </li>
            {%endfor%}
        </ul>
        


    </div>

        <a class="btn btn-warning" href="{% url 'basicapp:update' pk=school_detail.pk%}"> UPDATE SCHOOL </a>

        <a class="btn btn-danger" href="{% url 'basicapp:delete' pk=school_detail.pk%}"> DELETE SCHOOL </a>
     
        
{% endblock %}

cbv/basicapp/templates/basicapp/school_form.html
{% extends 'basicapp/base.html' %}

{% block body_block %}

    <h1>
        {% if not form.instance.pk %}
        Create School
        {% else %}
        Update School
        {% endif %}
    </h1>
    

    <div class="jumbotron">

    <form method="POST">
        {% csrf_token %}
        {{ form.as_ul }}

        <input type="submit" class="btn btn-primary" value="submit">

    </form>

    </div>

{% endblock %}

cbv/basicapp/templates/basicapp/school_list.html
{% extends 'basicapp/base.html' %}

{% block body_block %}

    <h2><span class="label label-default">List of schools</span></h2>

    <div class="panel panel-info " style="margin-top: 3%;">

        {% for school in schools %}
            <div class="well well-lg">
                <em><b><a href="{{school.id}}">{{school.name}}</a></b></em>
            </div>
        {% endfor %}
    
    </div>

    <div>
        <a href="{% url 'basicapp:create' %}" class="btn btn-primary"> 
            CREATE SCHOOL
        </a>


        <a href="{% url 'basicapp:create_student' %}" class="btn btn-success">
            ADD STUDENT 
        </a>   

    </div>


{% endblock %}

cbv/basicapp/templates/basicapp/student_confirm_delete.html
{% extends 'basicapp/base.html' %}


{% block body_block %}

    <h1>DELETE {{student.name}} ??</h1>
    <form method="POST">
        {% csrf_token %}

        <input type="submit" class="btn btn-danger" value="DELETE">

        <a href="{% url 'basicapp:detail' pk=student.school.pk %}">CANCEL</a>
    
    </form>

{% endblock%}

cbv/basicapp/templates/basicapp/student_form.html
{% extends 'basicapp/base.html' %}
{% block body_block %}

<div class="container">
    <div class="jumbotron">
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}

        <input type="submit" class="btn btn-primary" value="ADD">
    </form>
</div>
</div>

{% endblock %}

cbv/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BASE</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
<body>

    <nav class="navbar navbar-inverse navbar-static-top">
        <ul class="nav navbar-nav">

            <li><a class="navbar-brand" href="{% url 'admin:index' %}">ADMIN</a></li>

            <li><a class="navbar-link"  href="{% url 'basicapp:list' %}">SCHOOLS</a></li>




        </ul>

    </nav>
    <div class="container">
        
        {% block body_block %}


        {% endblock %}
        
    </div>
   
</body>
</html>

cbv/templates/index.html
{% extends 'base.html' %}

{% block body_block %}


<div class="jumbotron">
    <h1>HOME PAGE</h1>
</div>

{% endblock %}